### ISSUE TITLE
[Feature-request]: Add linter to CI

### ISSUE THREAD

**Issue by aviggiano** [crytic/properties#17]
### Describe the desired feature or improvement

The formatting of the codebase is inconsistent:

https://github.com/crytic/properties/blob/main/contracts/util/PropertiesHelper.sol#L184
```solidity
        if ( !(a < b)) {
```

https://github.com/crytic/properties/blob/main/contracts/util/PropertiesHelper.sol#L197
```solidity
        if(!(a <= b)) {
```

**Comment by aviggiano** [comment]
I would open a PR to fix this, but running `forge fmt` will output too many changes. It's probably better to a maintainer to do it with care

**Comment by montyly** [comment]
That's a great idea @aviggiano . @0xPhaze :maybe we can use prettier, similar to what we did for secure-contracts.com ?

**Comment by 0xPhaze** [comment]
@aviggiano you can have a look at how it's set up for [crytic/building-secure-contracts](https://github.com/crytic/building-secure-contracts):
- [package.json](https://github.com/crytic/building-secure-contracts/blob/f3b623e8220e524a11c2ae74e91140148c4596b8/package.json#L8-L15)
- [README.md](https://github.com/crytic/building-secure-contracts/blob/master/CONTRIBUTING.md#linting-and-formatting)
